package com.forresthopkinsa.braze.model

import com.forresthopkinsa.braze.model.DAO.ModConverter.ModEntity
import com.forresthopkinsa.braze.model.DAO.ModVersionConverter.ModVersionEntity
import javax.persistence.*

class DAO {

    interface DataEntity {
        fun component1(): Any? // ensures that this is a data class; componentN() functions are autogenerated
    }

    interface EntityConverter<T : DataEntity, U : Element> {
        fun fromElement(element: U): T
        fun fromEntity(entity: T): U
    }

    object ModConverter : EntityConverter<ModEntity, Mod> {

        @Entity
        @Table(name = "Mods")
        data class ModEntity(
                @Id
                val slug: String,

                @OneToMany(cascade = [CascadeType.ALL], fetch = FetchType.EAGER)
                @JoinColumn(name = "parent")
                val versions: List<ModVersionEntity>,

                var name: String,
                var author: String,
                var description: String,
                var link: String?,
                var donate: String?
        ) : DataEntity

        override fun fromElement(element: Mod): ModEntity = element.run {
            ModEntity(
                    slug = slug,
                    versions = versions.map(ModVersionConverter::fromElement),
                    name = name,
                    author = author,
                    description = description,
                    link = link,
                    donate = donate
            )
        }

        override fun fromEntity(entity: ModEntity): Mod = entity.run {
            Mod(
                    slug = slug,
                    name = name,
                    author = author,
                    description = description,
                    link = link,
                    donate = donate,
                    versions = versions.map(ModVersionConverter::fromEntity)
            )
        }

    }

    object ModVersionConverter : EntityConverter<ModVersionEntity, ModVersion> {

        @Entity
        @Table(name = "ModVersions")
        data class ModVersionEntity(
                @Id @GeneratedValue
                val id: Int = 0,

                @Enumerated(EnumType.STRING)
                var minForge: ForgeVersion,

                @Enumerated(EnumType.STRING)
                var maxForge: ForgeVersion,

                var versionName: String,
                var versionNumber: Int,
                var md5: String?,
                var size: Int?
        ) : DataEntity

        override fun fromEntity(entity: ModVersionEntity) = entity.run {
            ModVersion(
                    versionName = versionName,
                    versionNumber = versionNumber,
                    minForge = minForge,
                    maxForge = maxForge,
                    md5 = md5,
                    size = size,
                    dependencies = listOf() // todo
            )
        }

        override fun fromElement(element: ModVersion) = element.run {
            ModVersionEntity(
                    minForge = minForge,
                    maxForge = maxForge,
                    versionName = versionName,
                    versionNumber = versionNumber,
                    md5 = md5,
                    size = size
            )
        }
    }

}